[package]
name = "puniyu_logger"
version = "0.8.0"
description = "puniyu, logger核心实现"
authors = ["wuliya <3369906077@qq.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/puniyu/logger"
repository = "https://github.com/puniyu/logger"
edition = "2024"
rust-version = "1.88.0"

[dependencies]
convert_case = "0.11.0"
jiff = "0.2.34"
logforth = { version = "0.30.1", features = ["starter-log"] }
owo-colors = "4.3.0"
strip-ansi-escapes = "0.2.1"
log = "0.4.33"

[dev-dependencies]
serial_test = "3.5.0"




