set windows-shell := ["powershell.exe", "-c"]
set shell := ["bash", "-cu"]

build:
    cargo build --release -p puniyu_logger_ffi
    just _copy_lib

[unix]
_copy_lib:
    mkdir -p lib
    cp ../target/release/libpuniyu_logger_ffi.a lib/

[windows]
_copy_lib:
    New-Item -ItemType Directory -Force -Path lib | Out-Null
    Copy-Item ../target/release/puniyu_logger_ffi.lib lib/